[package]
name = "Lodestone"
version = "0.1.0"
edition = "2021"

exclude = [
    "target/*",
    "InstanceTest/*"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minreq = { version = "2.4.2", features = ["punycode","https-rustls-probe"] }
serde = { version = "1.0", features = ["derive"] }
chashmap = "2.2.2"
regex = "1.5.4"

reqwest = { version = "0.11.3", features = ["stream"] }
futures-util = "0.3.14"
indicatif = "0.15.0"

fs_extra = "1.2.0"

uuid = "0.8.2"
sanitize-filename = "0.3.0"
rust-crypto = "^0.2"
# rocket_cors = "0.5.1"

sys-info = "0.9.1"
systemstat = "0.1.10"
downloader = "0.2.6"

[dependencies.mongodb]
version = "2.0.0"
default-features = false
features = ["sync"]

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json", "tls"]