[global.tls]
certs = "private/rsa_sha256_cert.pem"
key = "private/rsa_sha256_key.pem"

[gloabl.tls.mutual]
ca_certs = "private/ca_cert.pem"

[staging]
port = 80

[production]
port = 80
log = "critical"