name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Backend
      run: cargo build --verbose --release
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Lodestone
        path: ./backend/target/release/Lodestone